#pragma once

#define IDC_STATIC                              (-1)

#define IDR_NAVKITMENU                          10000
#define IDM_FILE_OPEN_SCENE                     1000
#define IDM_FILE_OPEN_OBJ                       1001
#define IDM_FILE_OPEN_NAVP                      1002
#define IDM_FILE_OPEN_AIRG                      1003
#define IDM_FILE_SAVE_SCENE                     1010
#define IDM_FILE_SAVE_OBJ                       1011
#define IDM_FILE_SAVE_NAVP                      1012
#define IDM_FILE_SAVE_AIRG                      1013
#define IDM_FILE_EXIT                           1020
#define IDM_EDIT_NAVP_STAIRS                    1100
#define IDM_EDIT_AIRG_CONNECT_WAYPOINT          1101
#define IDM_SETTINGS_NAVKIT                     1200
#define IDM_SETTINGS_SCENE                      1201
#define IDM_SETTINGS_RECAST                     1202
#define IDM_SETTINGS_OBJ                        1203
#define IDM_SETTINGS_AIRG                       1204
#define IDM_VIEW_NAVP_SHOW_NAVP                 1300
#define IDM_VIEW_NAVP_SHOW_INDICES              1301
#define IDM_VIEW_NAVP_SHOW_PF_EXCLUDE_BOXES     1302
#define IDM_VIEW_NAVP_SHOW_PF_SEED_POINTS       1303
#define IDM_VIEW_NAVP_SHOW_RECAST_DEBUG_INFO    1304
#define IDM_VIEW_OBJ_SHOW_OBJ                   1310
#define IDM_VIEW_AIRG_SHOW_AIRG                 1320
#define IDM_VIEW_AIRG_SHOW_INDICES              1321
#define IDM_VIEW_AIRG_SHOW_GRID                 1322
#define IDM_VIEW_AIRG_SHOW_RECAST_DEBUG_INFO    1323
#define IDM_VIEW_AIRG_CELL_COLOR_OFF            1324
#define IDM_VIEW_AIRG_CELL_COLOR_BITMAP         1325
#define IDM_VIEW_AIRG_CELL_COLOR_VISION_DATA    1326
#define IDM_VIEW_AIRG_CELL_COLOR_LAYER          1327
#define IDM_VIEW_LOG_SHOW_LOG                   1330
#define IDM_VIEW_SCENE_SHOW_BBOX                1340
#define IDM_EXTRACT_SCENE                       1400
#define IDM_EXTRACT_SCENE_AND_BUILD_OBJ         1401
#define IDM_EXTRACT_SCENE_AND_BUILD_ALL         1402
#define IDM_BUILD_OBJ_FROM_SCENE                1500
#define IDM_BUILD_OBJ_FROM_NAVP                 1501
#define IDM_BUILD_BLEND_FROM_SCENE				1502
#define IDM_BUILD_NAVP                          1510
#define IDM_BUILD_AIRG                          1520
#define IDM_HELP_ABOUT                          1600

#define IDD_ERROR_DIALOG                        20000
#define IDC_ERROR_TEXT                          20001
#define IDC_COPY_BUTTON                         20002
#define IDI_APPICON                             20003
#define IDD_UPDATE_DIALOG                       20010
#define IDD_UPDATE_DIALOG                       20010
#define IDC_UPDATE_TEXT                         20011

#define IDD_NAVKIT_SETTINGS                     30000
#define IDC_SLIDER_BG_COLOR                     30001
#define IDC_BUTTON_BROWSE_HITMAN                30002
#define IDC_BUTTON_BROWSE_OUTPUT                30003
#define IDC_BUTTON_BROWSE_BLENDER               30004
#define IDC_APPLY                               30005
#define IDC_EDIT_HITMAN_PATH                    30006
#define IDC_EDIT_OUTPUT_PATH                    30007
#define IDC_EDIT_BLENDER_PATH                   30008
#define IDC_BG_COLOR_TEXT                       30010
#define IDC_HITMAN_DIR_TEXT                     30011
#define IDC_OUTPUT_DIR_TEXT                     30012
#define IDC_BLENDER_PATH_TEXT                   30013
#define IDC_BUTTON_RESET_DEFAULTS               30014

#define IDD_AIRG_MENU                           30100
#define IDC_SLIDER_SPACING                      30101
#define IDC_SLIDER_XOFFSET                      30102
#define IDC_SLIDER_ZOFFSET                      30103
#define IDC_STATIC_SPACING_VAL                  30104
#define IDC_STATIC_XOFFSET_VAL                  30105
#define IDC_STATIC_ZOFFSET_VAL                  30106

#define IDD_SCENE_MENU                          30200
#define IDC_SLIDER_BBOX_POS_X                   30201
#define IDC_SLIDER_BBOX_POS_Y                   30202
#define IDC_SLIDER_BBOX_POS_Z                   30203
#define IDC_SLIDER_BBOX_SCALE_X                 30204
#define IDC_SLIDER_BBOX_SCALE_Y                 30205
#define IDC_SLIDER_BBOX_SCALE_Z                 30206
#define IDC_STATIC_BBOX_POS_X_VAL               30207
#define IDC_STATIC_BBOX_POS_Y_VAL               30208
#define IDC_STATIC_BBOX_POS_Z_VAL               30209
#define IDC_STATIC_BBOX_SCALE_X_VAL             30210
#define IDC_STATIC_BBOX_SCALE_Y_VAL             30211
#define IDC_STATIC_BBOX_SCALE_Z_VAL             30212

#define IDD_RECAST_MENU                         30300
#define IDC_SLIDER_CELL_SIZE                    30301
#define IDC_SLIDER_CELL_HEIGHT                  30302
#define IDC_STATIC_CELL_SIZE_VAL                30303
#define IDC_STATIC_CELL_HEIGHT_VAL              30304
#define IDC_SLIDER_AGENT_HEIGHT                 30305
#define IDC_SLIDER_AGENT_RADIUS                 30306
#define IDC_SLIDER_AGENT_MAX_CLIMB              30307
#define IDC_SLIDER_AGENT_MAX_SLOPE              30308
#define IDC_STATIC_AGENT_HEIGHT_VAL             30309
#define IDC_STATIC_AGENT_RADIUS_VAL             30310
#define IDC_STATIC_AGENT_MAX_CLIMB_VAL          30311
#define IDC_STATIC_AGENT_MAX_SLOPE_VAL          30312
#define IDC_SLIDER_REGION_MIN_SIZE              30313
#define IDC_SLIDER_REGION_MERGE_SIZE            30314
#define IDC_STATIC_REGION_MIN_SIZE_VAL          30315
#define IDC_STATIC_REGION_MERGE_SIZE_VAL        30316
#define IDC_RADIO_PARTITION_WATERSHED           30317
#define IDC_RADIO_PARTITION_MONOTONE            30318
#define IDC_RADIO_PARTITION_LAYERS              30319
#define IDC_CHECK_FILTER_LOW_HANGING            30320
#define IDC_CHECK_FILTER_LEDGE_SPANS            30321
#define IDC_CHECK_FILTER_WALKABLE_LOW           30322
#define IDC_SLIDER_POLY_MAX_EDGE_LEN            30323
#define IDC_SLIDER_POLY_MAX_EDGE_ERR            30324
#define IDC_SLIDER_POLY_VERTS_PER_POLY          30325
#define IDC_STATIC_POLY_MAX_EDGE_LEN_VAL        30326
#define IDC_STATIC_POLY_MAX_EDGE_ERR_VAL        30327
#define IDC_STATIC_POLY_VERTS_PER_POLY_VAL      30328
#define IDC_SLIDER_DETAIL_SAMPLE_DIST           30329
#define IDC_SLIDER_DETAIL_SAMPLE_MAX_ERR        30330
#define IDC_STATIC_DETAIL_SAMPLE_DIST_VAL       30331
#define IDC_STATIC_DETAIL_SAMPLE_MAX_ERR_VAL    30332
#define IDC_SLIDER_TILING_TILE_SIZE             30333
#define IDC_STATIC_TILING_TILE_SIZE_VAL         30334
#define IDC_STATIC_TILING_INFO_TILES            30335
#define IDC_STATIC_TILING_INFO_MAX_TILES        30336
#define IDC_STATIC_TILING_INFO_MAX_POLYS        30337

#define IDD_OBJ_SETTINGS                        30400
#define IDC_RADIO_MESH_TYPE_ALOC                30401
#define IDC_RADIO_MESH_TYPE_PRIM                30402
#define IDC_CHECK_PRIM_LOD_1                    30403
#define IDC_CHECK_PRIM_LOD_2                    30404
#define IDC_CHECK_PRIM_LOD_3                    30405
#define IDC_CHECK_PRIM_LOD_4                    30406
#define IDC_CHECK_PRIM_LOD_5                    30407
#define IDC_CHECK_PRIM_LOD_6                    30408
#define IDC_CHECK_PRIM_LOD_7                    30409
#define IDC_CHECK_PRIM_LOD_8                    30410
