#pragma once

#define IDR_NAVKITMENU                          10000
#define IDM_FILE_OPEN_SCENE                     1000
#define IDM_FILE_OPEN_OBJ                       1001
#define IDM_FILE_OPEN_NAVP                      1002
#define IDM_FILE_OPEN_AIRG                      1003
#define IDM_FILE_SAVE_SCENE                     1010
#define IDM_FILE_SAVE_OBJ                       1011
#define IDM_FILE_SAVE_NAVP                      1012
#define IDM_FILE_SAVE_AIRG                      1013
#define IDM_FILE_EXIT                           1020
#define IDM_EDIT_NAVP_STAIRS                    1100
#define IDM_SETTINGS_NAVKIT                     1200
#define IDM_SETTINGS_SCENE                      1201
#define IDM_SETTINGS_NAVP                       1202
#define IDM_SETTINGS_AIRG                       1203
#define IDM_VIEW_NAVP_SHOW_NAVP                 1300
#define IDM_VIEW_NAVP_SHOW_INDICES              1301
#define IDM_VIEW_NAVP_SHOW_PF_EXCLUDE_BOXES     1302
#define IDM_VIEW_NAVP_SHOW_PF_SEED_POINTS       1303
#define IDM_VIEW_NAVP_SHOW_RECAST_DEBUG_INFO    1304
#define IDM_VIEW_OBJ_SHOW_OBJ                   1310
#define IDM_VIEW_AIRG_SHOW_AIRG                 1320
#define IDM_VIEW_AIRG_SHOW_INDICES              1321
#define IDM_VIEW_AIRG_SHOW_GRID                 1322
#define IDM_VIEW_AIRG_SHOW_RECAST_DEBUG_INFO    1323
#define IDM_VIEW_AIRG_CELL_COLOR_OFF            1324
#define IDM_VIEW_AIRG_CELL_COLOR_BITMAP         1325
#define IDM_VIEW_AIRG_CELL_COLOR_VISION_DATA    1326
#define IDM_VIEW_AIRG_CELL_COLOR_LAYER          1327
#define IDM_VIEW_LOG_SHOW_LOG                   1330
#define IDM_EXTRACT_SCENE                       1400
#define IDM_EXTRACT_SCENE_AND_BUILD_OBJ         1401
#define IDM_EXTRACT_SCENE_AND_BUILD_ALL         1402
#define IDM_BUILD_OBJ_FROM_SCENE                1500
#define IDM_BUILD_OBJ_FROM_NAVP                 1501
#define IDM_BUILD_NAVP                          1510
#define IDM_BUILD_AIRG                          1520
#define IDM_HELP_ABOUT                          1600

#define IDD_ERROR_DIALOG                        20000
#define IDC_ERROR_TEXT                          20001
#define IDC_COPY_BUTTON                         20002
#define IDD_UPDATE_DIALOG                       20010
#define IDC_UPDATE_TEXT                         20011

#define IDD_SETTINGS                            30000

#define IDC_SLIDER_BG_COLOR                     30001
#define IDC_BUTTON_BROWSE_HITMAN                30002
#define IDC_BUTTON_BROWSE_OUTPUT                30003
#define IDC_BUTTON_BROWSE_BLENDER               30004
#define IDC_APPLY                               30005
#define IDC_EDIT_HITMAN_PATH                    30006
#define IDC_EDIT_OUTPUT_PATH                    30007
#define IDC_EDIT_BLENDER_PATH                   30008
#define IDC_BG_COLOR_TEXT                       30010
#define IDC_HITMAN_DIR_TEXT                     30011
#define IDC_OUTPUT_DIR_TEXT                     30012
#define IDC_BLENDER_PATH_TEXT                   30013
