#ifndef GLACIER2OBJ_H
#define GLACIER2OBJ_H

/* This file is automatically generated by cbindgen. DO NOT EDIT. */

#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>
struct PartitionManager;

struct EntitiesJson;

template<typename T = void>
struct HashSet;

struct String;

extern "C" {

int run_extraction_wrapper(const char *retail_directory,
                           const char *game_version,
                           const char *nav_json_file,
                           const char *runtime_directory,
                           const char *output_directory,
                           const char *output_type,
                           void (*log_callback)(const char*));

EntitiesJson *build_from_nav_json_file(const char *nav_json_file,
                                       void (*log_callback)(const char*));

void free_entities_json(EntitiesJson *ptr);

HashSet<String> *get_all_aloc_or_prim_hashes(const EntitiesJson *entities_json,
                                             const char *output_folder,
                                             const char *output_type,
                                             void (*log_callback)(const char*));

void free_hashset_string(HashSet<String> *ptr);

PartitionManager *scan_packages(const char *retail_folder,
                                const char *game_version,
                                void (*log_callback)(const char*));

void free_partition_manager(PartitionManager *ptr);

void extract_alocs_or_prims(const char *runtime_folder,
                            HashSet<String> *needed_hashes,
                            const PartitionManager *partition_manager,
                            const char *output_folder,
                            const char *output_type,
                            void (*log_callback)(const char*));

} // extern "C"

#endif // GLACIER2OBJ_H
