#ifndef NAVKIT_RPKG_LIB_H
#define NAVKIT_RPKG_LIB_H

/* This file is automatically generated by cbindgen. DO NOT EDIT. */

#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>
struct PartitionManager;

struct EntitiesJson;

template<typename T = void>
struct HashSet;

struct String;

struct RustStringList {
  char **entries;
  uintptr_t length;
};

extern "C" {

int extract_scene_mesh_resources(const char *nav_json_file,
                                 const char *runtime_directory,
                                 const PartitionManager *partition_manager,
                                 const char *output_directory,
                                 const char *output_type,
                                 void (*log_callback)(const char*));

void extract_resources_from_rpkg(const char *runtime_folder,
                                 const char *const *needed_hashes,
                                 uintptr_t needed_hashes_len,
                                 const PartitionManager *partition_manager,
                                 const char *output_folder,
                                 const char *resource_type,
                                 void (*log_callback)(const char*));

PartitionManager *scan_packages(const char *retail_folder,
                                const char *game_version,
                                void (*log_callback)(const char*));

RustStringList *get_all_resources_hashes_by_type_from_rpkg_files(const PartitionManager *partition_manager,
                                                                 const char *resource_type,
                                                                 void (*log_callback)(const char*));

const char *get_string_from_list(RustStringList *list, uintptr_t index);

void free_entities_json(EntitiesJson *ptr);

void free_hashset_string(HashSet<String> *ptr);

void free_partition_manager(PartitionManager *ptr);

} // extern "C"

#endif // NAVKIT_RPKG_LIB_H
