name: CMake Build

on:
  push:
    tags:
      - '*'
  release:
    types: [ created ]
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        preset: [ x64-debug ]
    steps:
      - name: Set up CMake
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: "~3.28.0"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup VS environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Build and install debug
        run: |
          cmake --preset x64-debug .
          cmake --build build/x64-debug -j12
          cmake --install build/x64-debug --prefix _install/debug

      - name: Build and install release
        run: |
          cmake --preset x64-release .
          cmake --build build/x64-release -j12
          cmake --install build/x64-release --prefix _install/release

      - name: Copy debug artifacts
        run: |
          mkdir _dist-debug
          Copy-Item _install/debug/* -Destination _dist-debug/ -Recurse
          Remove-Item -Path _dist-debug/cmake_install.cmake -Force -Recurse -ErrorAction SilentlyContinue
          Remove-Item -Path _dist-debug/CMakeFiles -Force -Recurse -ErrorAction SilentlyContinue

      - name: Copy release artifacts
        run: |
          mkdir _dist-release
          Copy-Item _install/release/* -Destination _dist-release/ -Recurse
          Remove-Item -Path _dist-release/cmake_install.cmake -Force -Recurse -ErrorAction SilentlyContinue
          Remove-Item -Path _dist-release/CMakeFiles -Force -Recurse -ErrorAction SilentlyContinue

      - name: Archive debug NavKit
        uses: actions/upload-artifact@v4
        with:
          name: NavKit-Debug
          path: _dist-debug/*

      - name: Archive release Navkit
        uses: actions/upload-artifact@v4
        with:
          name: NavKit-Release
          path: _dist-release/*

  upload_release:
    name: Upload artifacts
    needs: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        artifact:
          - NavKit-Release
          - NavKit-Debug

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.artifact }}
          path: ${{ matrix.artifact }}

      - name: Archive artifact files
        run: |
          cd ${{ matrix.artifact }}
          zip -r ${{ matrix.artifact }}.zip *
